# Generated by Django 3.1 on 2020-09-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200908_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('PH', 'Phone'), ('TB', 'Tablet')], default='PH', max_length=2),
        ),
    ]
