# Generated by Django 3.1 on 2020-09-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('PH', 'Phone'), ('TB', 'Tablet'), ('LT', 'Laptop')], default='PH', max_length=2),
        ),
    ]
